name: continuous-integration

on: pull_request

jobs:
  ctest-mac:
    runs-on: macos-latest
    env:
      BUILD_DIR: mac-build

    steps:
    - name: get-buffy
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: get-build-deps
      run: |
        env
        brew install cmake llvm

    - name: make-buffy
      run: |
        cmake -E remove_directory "${BUILD_DIR}"
        cmake -B "${BUILD_DIR}" -S . -DCMAKE_BUILD_TYPE=Debug
        cmake --build "${BUILD_DIR}"

    - name: ctest
      working-directory: ${{env.BUILD_DIR}}
      run: ctest

  ctest-linux:
    runs-on: ubuntu-20.04
    env:
      BUILD_DIR: build

    steps:
    - name: get-buffy
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: get-build-deps
      run: |
        sudo apt-get install -y cmake valgrind

    - name: make-buffy
      run: |
        env
        cmake -E remove_directory "${BUILD_DIR}"
        cmake -B "${BUILD_DIR}" -S . -DCMAKE_BUILD_TYPE=Debug
        cmake --build "${BUILD_DIR}"

    - name: ctest
      working-directory: ${{env.BUILD_DIR}}
      run: ctest

    - name: ctest-valgrind
      working-directory: ${{env.BUILD_DIR}}
      run: ctest -D ExperimentalMemCheck

  scan-build:

    runs-on: ubuntu-20.04
    env:
      BUILD_DIR: scan-build

    steps:
    - name: get-buffy
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: get-build-deps
      run: |
        sudo apt-get install -y cmake clang clang-tools

    - name: scan-build-cmake
      run: |
        env
        cmake -E remove_directory "${BUILD_DIR}"
        scan-build cmake -B "${BUILD_DIR}" -S . -DCMAKE_BUILD_TYPE=Debug

    - name: scan-build-make
      working-directory: ${{env.BUILD_DIR}}
      run: |
        scan-build --status-bugs make

